import { Schema, model, mongoose } from "mongoose";

const userSchema = new Schema(
  {
    first_name: { type: String, required: true },
    last_name: { type: String, required: true },
    father_name: { type: String, required: true },
    title: { type: String, required: true },
    lu_role: {
      type: String,
      enum: ["Student", "Alumni", "Academic Staff", "Administrative Staff"],
      required: false,
    },
    uni_role: {
      type: String,
      enum: [
        "LU Student",
        "LU Alumni",
        "LU Academic Staff",
        "LU Administrative Staff",
        "Not LU Student",
      ],
      required: true,
    },
    gender: { type: String, enum: ["Male", "Female"], required: true },
    phone: { type: String, required: true },
    date_of_birth: { type: Date, min: "1900-01-01", required: true },
    nationality: { type: String, required: true },
    residence: { type: String, required: true },
    student_id: { type: Number, required: true },
    special_needs: { type: Boolean, required: true },
    uni_email: {
      type: String,
      trim: true,
      lowercase: true,
      unique: true,
      required: false,
    },
    active_email: {
      type: String,
      trim: true,
      lowercase: true,
      unique: true,
      required: "Email address is required",
    },
    faculty: {
      type: String,
      enum: [
        "Tourism and Hospitality Management",
        "Information",
        "Letters and Human Sciences",
        "Pedagogy",
        "Technology",
        "Law and Political and Administrative Sciences",
        "Agronomy",
        "Public Health",
        "Pharmacy",
        "Science",
        "Economics and Business Administration",
        "Medical Science",
        "Fine Arts and Architecture",
        "Engineering",
        "Dental Medicine",
      ],
      required: true,
    },
    branch: {
      type: String,
      enum: [
        "Deanship",
        "1st Branch",
        "2nd Branch",
        "3rd Branch",
        "4th Branch",
        "5th Branch",
        "6th Branch",
        "Centre MINE Hadath",
        "Centre MINE Tripoli",
        "Center for Languages and Translation",
        "Center of Language Sciences and Communication",
        "Filière - French Section",
        "Restoration Center",
        "Online",
      ],
      required: true,
    },
    verified: { type: Boolean, required: false },
    is_lu_students: { type: Boolean, required: true },
    event: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Events",
      required: false,
    },
    opportunity: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Opprtunities",
      required: false,
    },
    password: { type: String, required: true },
    token: { type: String },
  },
  {
    collection: "Users",
    timestamps: true,
  }
);
const User = model("User", userSchema);
export default User;
